"""Initial migration: Create scribes and entries tables

Revision ID: 57fa912027af
Revises: 
Create Date: 2025-11-17 22:11:02.421912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57fa912027af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scribes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scribes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scribes_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_scribes_username'), ['username'], unique=True)

    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('scribe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scribe_id'], ['scribes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entries_scribe_id'), ['scribe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entries_scribe_id'))

    op.drop_table('entries')
    with op.batch_alter_table('scribes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scribes_username'))
        batch_op.drop_index(batch_op.f('ix_scribes_email'))

    op.drop_table('scribes')
    # ### end Alembic commands ###
