"""Convert Scribe and Entry IDs to UUID

Revision ID: 7c8a24773b66
Revises: 57fa912027af
Create Date: 2025-11-21 21:11:42.999766

IMPORTANT: This migration is ONLY safe for empty databases with no existing data.
It converts ID columns from INTEGER to String(36) to support UUIDs, but does NOT
migrate existing integer IDs to UUID format.

Since there is no production deployment yet, this migration assumes the database
is empty. If you have existing data, you must either:
1. Clear the database before running this migration, OR
2. Write a more complex migration that:
   - Creates new UUID columns
   - Generates UUIDs for existing records
   - Updates foreign key references
   - Drops old columns and constraints
   - Renames new columns to replace old ones

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8a24773b66'
down_revision = '57fa912027af'
branch_labels = None
depends_on = None


def upgrade():
    # WARNING: This migration assumes an empty database with no existing data.
    # It will NOT properly convert existing integer IDs to UUIDs.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('scribe_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('scribes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # WARNING: This downgrade assumes UUID values can be converted back to integers.
    # This will only work correctly if the database was empty when upgrade() was run.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scribes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('scribe_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
